services:
  ollama:
    image: ollama/ollama:latest
    container_name: deepseek-ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-20G}
        reservations:
          memory: ${MEMORY_RESERVE:-4G}
    networks:
      - deepseek-network

  # Opcional: Interface web para usar os modelos
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: deepseek-webui
    ports:
      - "${WEBUI_PORT:-3000}:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - deepseek-network

volumes:
  ollama-data:
    driver: local
  open-webui-data:
    driver: local

networks:
  deepseek-network:
    driver: bridge